const clientDB = {
    "chithanh": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_pro_chithanh",
        "port": 3306,
    },
    "peeair4_2024": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_pro_peeair4_2024",
        "port": 3306,
    },


    // "dev": {
    //     "host": "mariadb-202130-0.cloudclusters.net",
    //     "user": "soubin",
    //     "password": "zaq1@wsx",
    //     "database": "dcommerce_dev",
    //     "port": 10087,
    // },
    "dev": {
        "host": "localhost",
        "user": "root",
        "password": "SDAT@3480",
        "database": "dcommerce_dev",
        // "database": "dc_carcare_dev",
        "port": 3306,
    },
    "dev_online": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_pro_dongkhumzang_restaurant",
        "port": 3306,
    },
    "ksouk": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_pro_ksouk",
        "port": 3306,
    },
    "demo1": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_dem_1",
        "port": 3306,
    },
    "demo": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_demo",
        "port": 3306,
    },
    "standard": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_standard_model",
        "port": 3306,
    },
    "auto": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_pro_auto_55244451",
        "port": 3306,
    },
    "the_corners": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_pro_the_corners",
        "port": 3306,
    },
    "phaivanh": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_pro_phayvanh",
        "port": 3306,
    },
    "bmart": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_pro_bmart",
        "port": 3306,
    },
    "onphet": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_pro_onphet",
        "port": 3306,
    },
    "carcare_sokpaluang": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_pro_carcare_sokpaluang",
        "port": 3306,
    },
    "mpwt": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_mpwt",
        "port": 3306,
    },
    "taiphuan": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_pro_auto_02023838999",
        "port": 3306,
    },
    "pm": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_pro_pheuanmit",
        "port": 3306,
    },
    "best_coff": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_pro_best_coffee",
        "port": 3306,
    },
    "dcommerce": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": "dcommerce_pro_dc",
        "port": 3306,
    },
    "env_auto": {
        "host": "150.95.31.23",
        "user": "root",
        "password": "sdat@3480",
        "database": process.env.DB_NAME,
        "port": 3306,
    },

}

module.exports = {
    clientDB,
}